### ISSUE TITLE
Installing packages to opt and loading via `packadd`?

### ISSUE THREAD

**Issue by shaunsingh** [rktjmp/pact.nvim#7]
Hi, rather than loading packages immediately, is it possible to load packages via `packadd` and store them in `opt`?

I see there is some code in the repo to manage start vs. opt, but it doesn't have documentation yet

**Comment by rktjmp** [comment]
Yep. Should be able to mark them as opt with `(<provider> ... {:opt? true})`, (or `opt = true` in lua) looks like I missed it in the docs.

`pact` is unlikely (?) to get any kind of "auto load" stuff like Lazy though, so the `packadd` call must be done manually - mostly because I don't use opt much so to add it, it would have to annoy me enough for me to add it.

I did just spot a bug where opt "afters" will try to run but the package wont be loaded though.

**Comment by shaunsingh** [comment]
> pact is unlikely (?) to get any kind of "auto load" stuff like Lazy though, so the packadd call must be done manually - mostly because I don't use opt much so to add it, it would have to annoy me enough for me to add it.

Thanks, I'm wrapping pact with my own set of macros/autocommands to provide some of the functionality lazy does. I just wanted something to install and manage semver plugins which pact handles *perfectly*. Thanks for the awesome package manager!

**Comment by rktjmp** [comment]
Be careful, there is a lot of changes coming in the next version, particularly around how pact manages its own data folders to support transactions and the way you define packages will change.

The next version _currently_ just hard-error with a "please reinstall pact from scratch" if it encounters the old style which might effect your downstream. Automatic migration might or might not appear.

```fennel
;; 0.0.10 estimation
(make-pact ; must now wrap calls in make-pact/make_pact for technical reasons
  ;; possibly able to specify "meta-package" name here or table with meta-package options 
  ;; simpler package specification format
  (github :some/package) ; track head
  (github :some/package <cons> {optional-table})) ; where cons is "branch" "#tag"  "^commit" (including "short-shas") or ">ver"
```

I assume you're just testing the waters a bit, not sure I would recommend pushing pact into a distro yet.

**Comment by shaunsingh** [comment]
> I did just spot a bug where opt "afters" will try to run but the package wont be loaded though.

If a package is opt, and then manually loaded via `packadd` afterwards, will pact run its `:after` block when its loaded?

**Comment by rktjmp** [comment]
Not currently, AFAIK it would require writing some autocommand hook to watch for the packadd then running the after - only one time. Lot of book keeping and general guts that I don't think belongs in pact. 

Likely pact will automatically `packadd x` if it's `opt` before running after.

I've adjusted how tasks are scheduled in the next version too so you wont have to schedule-wrap unsafe calls in after anymore.

**Comment by rktjmp** [comment]
Sorry, had other code get in the way. `main` is sort of 0.0.10, but it has some bugs around nvim_echoing errors in transactions, and honestly, I have very little want to fix it at the moment, and my usage with package managers is ~once per month so the features like lockfiles and such have very little force behind them for me personally.

I would recommend you look to other tooling for nyoom if you have not already.
