### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by TheBearodactyl** [rktjmp/pact.nvim#8]
Error detected while processing /home/emi/.config/nvim/init.lua:
E5112: Error while creating lua chunk: /home/emi/.config/nvim/init.lua:4: ')' expected (to close '(' at line 2) near 'vim'

**Comment by rktjmp** [comment]
Looks like this needs a comma after it

```
  vim.notify(
    string.format("Could not find pact.nvim, cloning new copy to %s", check_path)
    vim.log.levels.WARN
  )
```
to

```
  vim.notify(
    string.format("Could not find pact.nvim, cloning new copy to %s", check_path),
    vim.log.levels.WARN
  )
```

**Comment by TheBearodactyl** [comment]
thanks :D
